language: cpp

install:
  - sudo apt update
  - sudo apt install cmake

script:
  - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
  - echo $CHANGED_FILES
  - for file in $CHANGED_FILES; do
    dir=$(dirname $file);
    echo $dir;
    done
  - if test -f ($dir/CMakeLists.txt); then
    ./scripts/buildProjectAtDir.sh $dir
    fi
